### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by jzuhone** [pozil/codetour-watch#10]
Getting the following issue:

```
with:
    repo-token: ***
    silent: false
    tour-path: .tours/
    fail-on-missing-tour-updates: false
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/pozil/codetour-watch/v1.6.[3](https://github.com/yt-project/yt/actions/runs/3426987744/jobs/5839717454#step:3:3)/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async commentPr (/home/runner/work/_actions/pozil/codetour-watch/v1.6.3/src/index.js:171:9)
    at async run (/home/runner/work/_actions/pozil/codetour-watch/v1.6.3/src/index.js:75:13) {
  status: [4](https://github.com/yt-project/yt/actions/runs/3426987744/jobs/5839717454#step:3:4)03,
```

**Comment by pozil** [comment]
Hi @jzuhone, looking at your logs I believe that you made a mistake in the version tag.
This line is missing the patch version (the last digit of the version number):
```
at /home/runner/work/_actions/pozil/codetour-watch/v1.6.
```

FYI you can either use the complete version tag or the branch name in your config:
```
uses: pozil/codetour-watch@master
```

**Comment by pozil** [comment]
@jzuhone please disregard my last comments.

Based on the error message and the source code (`index.js:71`), the GitHub token that is provided to the action does not allow it to create a comment.
```js
await octokit.rest.issues.createComment(commentInfo);
```

You may need to change your repo settings to allow this comment or provide a personal access token to the action.
